env:
  import_path: imp_marl.environments.owf_sens_env.OWF_Sens
  config_file: owf_default_env.yaml
agent:
  preset: inspection
  params:
    inspection_interval: 1
    n_components: 2
runner:
  n_agents: 2
  pf_slice: [0, 2]
  init_inspection_age: 61
evaluation:
  episodes: 20
sweep:
  params:
    inspection_interval:
      range: [1, 21]
      step: 1
    n_components:
      values: [1, 2]
  episodes: 100
  boot_iters: 2000
  max_workers: 1
output:
  path: ../results/test_series_01.json
